CREATE TABLE Courses
(
	ID INT PRIMARY KEY IDENTITY,
	Name VARCHAR(20) UNIQUE
);

CREATE TABLE Cycles
(
	ID INT PRIMARY KEY IDENTITY,
	BeginningDate DATE,
	Price DECIMAL (7,2),
	Course_ID INT FOREIGN KEY REFERENCES Courses(ID)
);

CREATE TABLE Study_Days
(
	ID INT PRIMARY KEY IDENTITY,
	Cycle_ID INT FOREIGN KEY REFERENCES Courses(ID),
	DayInWeek VARCHAR(20),
	BeginHour TIME,
	EndHour TIME,
	CONSTRAINT uq_Study_Days UNIQUE(Cycle_ID, DayInWeek, BeginHour, EndHour)
);

CREATE TABLE Lecturers
(
	ID INT PRIMARY KEY IDENTITY,
	IdentityNumber VARCHAR(15) UNIQUE,
	FirstName NVARCHAR(20),
	LastName NVARCHAR(20),
	HourlyRate DECIMAL(5,2)
);

CREATE TABLE Subjects
(
	ID INT PRIMARY KEY IDENTITY,
	SubjectName VARCHAR(20) UNIQUE,
	TotalHours INT,
);

CREATE TABLE LecturersInSubjects
(
	ID INT PRIMARY KEY IDENTITY,
	Lecturer_ID INT FOREIGN KEY REFERENCES Lecturers(ID),
	Subject_ID INT FOREIGN KEY REFERENCES Subjects(ID),
);

CREATE TABLE SubjectsInCycles
(
	ID INT PRIMARY KEY IDENTITY,
	Cycle_ID INT FOREIGN KEY REFERENCES Cycles(ID),
	Subject_ID INT FOREIGN KEY REFERENCES Subjects(ID),

);

CREATE TABLE Students
(
	ID INT PRIMARY KEY IDENTITY,
	IdentityNumber VARCHAR(15) UNIQUE,
	FirstName NVARCHAR(20),
	LastName NVARCHAR(20),
	Phone VARCHAR(15),
	Balance Decimal(8,2)
);

CREATE TABLE StudentsInCycles
(
	ID INT PRIMARY KEY IDENTITY,
	Cycle_ID INT FOREIGN KEY REFERENCES Cycles(ID),
	Students_ID INT FOREIGN KEY REFERENCES Students(ID),
);

CREATE TABLE Payments
(
	ID INT PRIMARY KEY IDENTITY,
	TotalPayment DECIMAL(8,2),
	Cycle_ID INT FOREIGN KEY REFERENCES Cycles(ID),
	Students_ID INT FOREIGN KEY REFERENCES Students(ID),
);

CREATE TABLE IntrestedClients
(
	ID INT PRIMARY KEY IDENTITY,
	IdentityNumber VARCHAR(15) UNIQUE,
	FirstName NVARCHAR(20),
	LastName NVARCHAR(20),
	Phone VARCHAR(15),
);